# Generated by Django 2.2 on 2019-05-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190505_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
