# Generated by Django 2.2 on 2019-05-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20190505_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
